#!/usr/bin/env sh

# Add changes to git.
git add -A

# Commit changes.
msg=":memo: Update: $(date +"%Y-%m-%d %H:%M:%S")"
if [ $# -eq 1 ]
  then msg="$1"
fi
git commit -q -m "$msg"

# Push source and build repos.
git push -q origin master
